#!/bin/bash

if [[ ! "$1" =~ [0-9]+ ]]
then
  echo "This script power cycles a visiongpu machine if it is unreachable."
  echo "It will not power cycle a machine that responds to pings."
  echo
  echo "Prerequisites:"
  echo "  (1) the ipmi vision password for serial access"
  echo
  echo "Usage: $0 server-number"
  exit 1
fi

SERVERNUM=$(printf '%02d' $1)
SERVERNAME=visiongpu${SERVERNUM}.csail.mit.edu
BMCNAME=bmc-visiongpu${SERVERNUM}
IPMIPASSFILE=${HOME}/.ipmitool/visionpw

# STEP 0: prerequisites
if [ ! -f "${IPMIPASSFILE}" ]
then
  echo "${IPMIPASSFILE} should contain the vision ipmi password."
  echo "Get it from somebody who has it. Not wiping."
  exit 1
fi

if [ $(stat -c %A "${IPMIPASSFILE}") != '-r--------' ]
then
  echo "${IPMIPASSFILE} should have 400 permissions."
  echo "Run chmod 400 ${IPMIPASSFILE}."
  exit 1
fi

# STEP 1: Check that the machine is not reachable
if ping -c1 ${SERVERNAME} > /dev/null
then
  echo "${SERVERNAME} is reachable.  Not power-cycling."
  exit 1
fi

# STEP 2: power cycle the amchine
ssh -x holyoke-console ipmitool -I lanplus -U vision -f ${IPMIPASSFILE} \
    -H ${BMCNAME} chassis power cycle
