USE_CUDNN := 1
USE_OPENCV := 1
OPENCV_VERSION := 3
ALLOW_LMDB_NOLOCK := 1
CUDA_DIR := /usr/local/cuda
CUDA_ARCH :=	-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_50,code=compute_50
BLAS := mkl
BLAS_INCLUDE := /opt/intel/mkl/include
BLAS_LIB := /opt/intel/mkl/lib/intel64
MATLAB_DIR := /afs/csail.mit.edu/system/common/matlab/latest/
PYTHON_INCLUDE := /usr/include/python2.7
PYTHON_LIB := /usr/lib
WITH_PYTHON_LAYER := 1
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include \
				/usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib \
				/usr/lib/x86_64-linux-gnu/hdf5/serial
BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
# enable pretty build (comment to see full commands)
Q ?= @
